sequenceDiagram
    participant browser
    participant server

    Note right of browser: client executing request

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{content: "HTML is easy", date: "2019-05-23T17:30:31.098Z"},…]
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/content.css
    activate server
    server-->>browser: the sytlesheet for data
    deactivate server

    Note right of browser: Client executing POST and receive request

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    Note right of browser: 302 Found with payload note: Birdie
    server-->>server: redirect and update data.json
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/note
    activate server
    server-->>browser: Updated HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: Updated [{content: "HTML is easy", date: "2019-05-23T17:30:31.098Z"},…]
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/content.css
    activate server
    server-->>browser: the sytlesheet for data
    deactivate server
